In [24]:
# n 變數 線性方程組
import numpy as np

In [25]:
#  3 * 3

# A=陣列數字
A = np.array([[1, -2, 3], [2, 1, -1], [-1, 1, 2]])
# B=陣列數字
b = np.array([[1], [3], [7]])
# to solve
x = np.linalg.solve(A, b)


print(

    f''' 

A= {A} 

b= {b} 

x= {x} 

''')

 

A= [[ 1 -2  3]
 [ 2  1 -1]
 [-1  1  2]] 

b= [[1]
 [3]
 [7]] 

x= [[0.9444]
 [3.3889]
 [2.2778]] 




In [26]:
#  5 * 5

# A=陣列數字
A = np.array([[1, -2, 3, 1, -2], [2, 1, -1, -1, 1],
             [-1, 1, 2, 2, -3], [2, 1, -1, -1, 2], [1, 3, -2, 2, -2]])
# B=陣列數字
b = np.array([[1], [3], [7], [5], [4]])
# to solve
x = np.linalg.solve(A, b)


print(

    f''' 

A= {A} 

b= {b} 

x= {x} 

''')

 

A= [[ 1 -2  3  1 -2]
 [ 2  1 -1 -1  1]
 [-1  1  2  2 -3]
 [ 2  1 -1 -1  2]
 [ 1  3 -2  2 -2]] 

b= [[1]
 [3]
 [7]
 [5]
 [4]] 

x= [[0.875]
 [4.125]
 [3.75 ]
 [1.125]
 [2.   ]] 




In [27]:
#  10 * 10

n = 10
np.random.seed(0)

A = np.random.randint(-3, 3, size=(n, n))


np.random.seed(1)

b = np.random.randint(-3, 8, size=(n, 1))

# to solve
x = np.linalg.solve(A, b)

print(

    f''' 

A= {A} 

b= {b} 

x= {x} 

''')

 

A= [[ 1  2 -3  0  0  0 -2  0  2 -1]
 [ 1 -3 -3  1 -1 -2 -3 -2  2 -2]
 [ 2 -3 -2  1  0 -3  0  2 -3 -1]
 [ 0 -3 -2  0  2  0  0 -3 -2 -2]
 [-2 -3 -1  1  0  0 -1  1 -1 -3]
 [-3  1  2  2 -3  1 -2  1 -2 -1]
 [-1 -3 -2 -2 -2 -2  0  0 -1  0]
 [-3  0  2  1 -2 -1  1  0  1  1]
 [ 1  0  1  1  1 -3  1  0 -1  2]
 [ 2  2 -3 -2  2 -2  0 -3  2 -3]] 

b= [[ 2]
 [ 5]
 [ 6]
 [ 2]
 [-3]
 [-3]
 [-2]
 [ 4]
 [ 3]
 [ 6]] 

x= [[ 1.6893]
 [ 0.6244]
 [-1.9299]
 [ 3.6887]
 [-2.6736]
 [-0.0933]
 [ 4.2903]
 [-1.4591]
 [ 0.4537]
 [-0.9455]] 




In [36]:
# %%

# when n is large, it is very slow!!


print(f'A= \n{A}')


def ryDet(A):

    n = A.shape[0]

    if n > 1:

        i = 0

        Bi = np.delete(A, i, axis=0)

        #print(f'\ni= {i}, Bi= \n{Bi}')

        det = 0

        for j in range(n):

            Bij = np.delete(Bi, j, axis=1)

            print(f'\ni,j= {i}{j}, Bij= \n{Bij}')

            Dij = ryDet(Bij)  # np.linalg.det(Bij)

            print(f'.... Dij= {Dij}')

            Cij = A[i, j]*Dij*(-1)**(i+j)

            det += Cij

        #print(f'det= {det}')

        return det

    elif A.shape[0] == 1:

        det = A[0, 0]

        return det

    else:

        return None


det = ryDet(A)

print(f'\ndet= {det}')

A= 
[[1 3 4]
 [2 1 3]
 [4 1 2]]

i,j= 00, Bij= 
[[1 3]
 [1 2]]

i,j= 00, Bij= 
[[2]]
.... Dij= 2

i,j= 01, Bij= 
[[1]]
.... Dij= 1
.... Dij= -1

i,j= 01, Bij= 
[[2 3]
 [4 2]]

i,j= 00, Bij= 
[[2]]
.... Dij= 2

i,j= 01, Bij= 
[[4]]
.... Dij= 4
.... Dij= -8

i,j= 02, Bij= 
[[2 1]
 [4 1]]

i,j= 00, Bij= 
[[1]]
.... Dij= 1

i,j= 01, Bij= 
[[4]]
.... Dij= 4
.... Dij= -2

det= 15


In [31]:
import os
import sys
import glob
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
%matplotlib inline
%precision 4
plt.style.use('ggplot')

In [32]:
import numpy as np
import scipy.linalg as la
np.set_printoptions(suppress=True)

A = np.array([[1,3,4],[2,1,3],[4,1,2]])

L = np.array([[1,0,0],[2,1,0],[4,11/5,1]])
U = np.array([[1,3,4],[0,-5,-5],[0,0,-3]])
print(L.dot(U))
print(L)
print(U)

[[1. 3. 4.]
 [2. 1. 3.]
 [4. 1. 2.]]
[[1.  0.  0. ]
 [2.  1.  0. ]
 [4.  2.2 1. ]]
[[ 1  3  4]
 [ 0 -5 -5]
 [ 0  0 -3]]


In [ ]:
import numpy as np
import scipy.linalg as la
np.set_printoptions(suppress=True)

A = np.array([[1,3,4],[2,1,3],[4,1,2]])

print(A)

P, L, U = la.lu(A)
print(np.dot(P.T, A))
print
print(np.dot(L, U))
print(P)
print(L)
print(U)

[[1 3 4]
 [2 1 3]
 [4 1 2]]
[[4. 1. 2.]
 [1. 3. 4.]
 [2. 1. 3.]]
[[4. 1. 2.]
 [1. 3. 4.]
 [2. 1. 3.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1.     0.     0.    ]
 [0.25   1.     0.    ]
 [0.5    0.1818 1.    ]]
[[4.     1.     2.    ]
 [0.     2.75   3.5   ]
 [0.     0.     1.3636]]


In [ ]:
A = np.array([[1,3,5],[3,13,23],[5,23,42]])
L = la.cholesky(A)
print(np.dot(L.T, L))

print(L)
print(A)

[[ 1.  3.  5.]
 [ 3. 13. 23.]
 [ 5. 23. 42.]]
[[1. 3. 5.]
 [0. 2. 4.]
 [0. 0. 1.]]
[[ 1  3  5]
 [ 3 13 23]
 [ 5 23 42]]


In [ ]:
A = np.array([[0,1,1],[2,1,0],[3,4,5]])

u, V = la.eig(A)
print(np.dot(V,np.dot(np.diag(u), la.inv(V))))
print(u)

[[-0.+0.j  1.+0.j  1.+0.j]
 [ 2.+0.j  1.+0.j  0.+0.j]
 [ 3.+0.j  4.+0.j  5.+0.j]]
[ 5.8541+0.j -0.8541+0.j  1.    +0.j]


In [ ]:
A = np.array([[0,1],[-1,0]])
print(A)

u, V = la.eig(A)
print(np.dot(V,np.dot(np.diag(u), la.inv(V))))
print(u)

[[ 0  1]
 [-1  0]]
[[ 0.+0.j  1.+0.j]
 [-1.+0.j  0.+0.j]]
[0.+1.j 0.-1.j]


In [ ]:
# If you know the eigenvalues must be real
# because A is a positive definite (e.g. covariance) matrix
# use real_if_close

A = np.array([[0,1,1],[2,1,0],[3,4,5]])
u, V = la.eig(A)
print(u)
print (np.real_if_close(u))

[ 5.8541+0.j -0.8541+0.j  1.    +0.j]
[ 5.8541 -0.8541  1.    ]


In [ ]:
A = np.array([[8,6,4,1],[1,4,5,1],[8,4,1,1],[1,4,3,6]])
b = np.array([19,11,14,14])
la.solve(A,b)

array([1., 1., 1., 1.])

In [ ]:
b = np.array([19.01,11.05,14.07,14.05])
la.solve(A,b)

array([-2.34 ,  9.745, -4.85 , -1.34 ])

In [ ]:
U, s, V = np.linalg.svd(A)
print(s)
print(max(s)/min(s))

[15.5457  6.9002  3.8363  0.0049]
3198.6725811994825


In [ ]:
# Your code here

def svdsolver(A,b):
    U, s, V = np.linalg.svd(A)
    if np.prod(s) == 0:
       print("Matrix is singular")
    else:
       return np.dot(np.dot((V.T).dot(np.diag(s**(-1))), U.T),b)

In [ ]:
A = np.array([[1,1],[1,2]])
b = np.array([3,1])
print(np.linalg.solve(A,b))
print(svdsolver(A,b))



[ 5. -2.]
[ 5. -2.]


In [ ]:
A = np.array([[1,2,3],[2,-4,6],[3,-9,-3]])   
AL = np.array([[1,0,0],[2,1,0],[3,15/8,1]])    
AU = np.array([[1,2,3],[0,-8,0],[0,0,-12]])   

print(A,AL,AU)


[[ 1  2  3]
 [ 2 -4  6]
 [ 3 -9 -3]] [[1.    0.    0.   ]
 [2.    1.    0.   ]
 [3.    1.875 1.   ]] [[  1   2   3]
 [  0  -8   0]
 [  0   0 -12]]


In [29]:
A = np.array([[1,2,3],[2,-4,6],[3,6,-3]]) 
print("non-positive definite matrix")

non-positive definite matrix
